// Conformance tests for the WP8 receipt export (ruvnet/autogenous#10)
// against the ADR-322C witness/receipt contract on ruflo main.
//
// Fixtures in test/fixtures/ are copied VERBATIM from ruvnet/ruflo
// v3/docs/spec/examples/ at merge commit
// df0c9821984b2b0f76ea0ea6eb6cfe5abda5bd54 (PR ruvnet/ruflo#3067). They
// were generated by ruflo's real implementation, so passing them is
// producer↔verifier interop, not self-agreement. SHA-256 of the copies:
//   receipt-accepted.example.json
//     fa90341963ac7833b889f8ed5db50d81ebca9af71ce3fc5e05d1f344b9e05167
//   receipt-bootstrap-reference.example.json
//     4d2fd409590373a2a2cf112805ba33e4537251a8d0b5cd4a541d773e2ac19fda
//
// Both fixtures expire at 2026-08-20T00:00:00.000Z, so fixture tests pin
// the verification clock inside their validity window.
// Checklist references (ruflo conformance-checklist.md) per test.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash, verify as edVerify } from 'node:crypto';
import { PeerIdentity } from '../src/transport.js';
import { evaluate, evolveMesh, promoteAuthorized, type EvolvableParams } from '../src/mesh-evolve.js';
import { DEFAULT_INDEPENDENCE_WEIGHTS } from '../src/lineage-independence.js';
import {
  BENCH_TASK_IDS,
  contentIdOf,
  decimal12,
  exportEvolutionReceipts,
  exportPromotionReceipt,
  jcsCanonicalize,
  recomputeStatistics,
  uuidV7,
  verifyExportedReceipt,
  RECEIPT_SIGNING_DOMAIN,
  type ExportedReceipt,
} from '../src/receipt-export.js';

const FIXTURE_CLOCK = new Date('2026-08-19T12:00:00.000Z');

function fixture(name: string): { doc: ExportedReceipt; raw: string } {
  const raw = readFileSync(new URL(`./fixtures/${name}`, import.meta.url), 'utf8');
  return { doc: JSON.parse(raw) as ExportedReceipt, raw };
}

const START: EvolvableParams = { weights: { ...DEFAULT_INDEPENDENCE_WEIGHTS }, quorumThreshold: 2.0 };

/** A promoted (candidate, decision) pair found deterministically. */
function promotedCandidate() {
  const result = evolveMesh(PeerIdentity.generate(), 42, 12);
  assert.ok(result.promotions >= 1, 'seed 42 must yield at least one promotion');
  return result;
}

function exportOne(identity = PeerIdentity.generate()) {
  const result = promotedCandidate();
  const receipts = exportEvolutionReceipts(result, {
    identity,
    lineageId: uuidV7(),
    attestor: 'autogenous/governed-loop',
    start: START,
    evaluateFn: evaluate,
  });
  assert.equal(receipts.length, result.promotions);
  const first = receipts[0]!;
  return { receipt: first, identity, result };
}

function pemOf(receipt: ExportedReceipt): string {
  return receipt.signature.publicKeyPem;
}

// ── interop with ruflo-produced records ─────────────────────────────────

test('B1..B5 interop: the ruflo accepted fixture verifies end to end under our verifier', () => {
  const { doc } = fixture('receipt-accepted.example.json');
  const { accepted } = verifyExportedReceipt(doc, [doc.signature.publicKeyPem], FIXTURE_CLOCK);
  assert.equal(accepted, true);
});

test('B5: the discriminating bootstrap-reference fixture recomputes byte-for-byte', () => {
  const { doc } = fixture('receipt-bootstrap-reference.example.json');
  const p = doc.payload as Record<string, unknown>;
  const statistics = p['statistics'] as Record<string, unknown>;
  const recomputed = recomputeStatistics({
    heldOutDeltas: p['heldOutDeltas'] as string[],
    baselineScore: p['baselineScore'] as string,
    candidateScore: p['candidateScore'] as string,
    frozenAnchorRegression: statistics['frozenAnchorRegression'] as string,
    iterations: statistics['iterations'] as number,
    corpusHash: p['corpusHash'] as string,
    candidateId: p['candidateId'] as string,
    baselineRef: p['baselineRef'] as string,
    evaluationRunId: p['evaluationRunId'] as string,
  });
  // The checklist's published expectations for this fixture.
  assert.equal(recomputed.seedHex, '167c9185d76163dfa69ae57c11af813669a6353abcb49d7af673acf918f3a7c3');
  assert.equal(recomputed.relativeLift, '0.100428571429');
  assert.equal(recomputed.pairedBootstrapProbability, '1');
  assert.equal(recomputed.pairedBootstrapDeltaCILow95, '0.0489');
  assert.equal(recomputed.accepted, true);
  // And the whole fixture passes the full verifier.
  verifyExportedReceipt(doc, [doc.signature.publicKeyPem], FIXTURE_CLOCK);
});

test('B1: one flipped byte in the fixture fails with a receipt content ID mismatch', () => {
  const { raw } = fixture('receipt-accepted.example.json');
  const tampered = JSON.parse(raw.replace('"0.08"', '"0.09"')) as ExportedReceipt;
  assert.throws(
    () => verifyExportedReceipt(tampered, [tampered.signature.publicKeyPem], FIXTURE_CLOCK),
    /receipt content ID mismatch/,
  );
});

test('B8: an expired fixture is refused at a clock past expiresAt', () => {
  const { doc } = fixture('receipt-accepted.example.json');
  assert.throws(
    () => verifyExportedReceipt(doc, [doc.signature.publicKeyPem], new Date('2026-08-20T00:00:00.000Z')),
    /expired/,
  );
});

// ── producer conformance of our own export ──────────────────────────────

test('A1/A4/A6: an exported promotion receipt verifies end to end', () => {
  const { receipt } = exportOne();
  const { receiptId } = verifyExportedReceipt(receipt, [pemOf(receipt)], new Date());
  assert.equal(receiptId, (receipt.payload as Record<string, unknown>)['receiptId']);
  // A6 independently: node crypto verifies the signature over
  // UTF8(domain) || 0x00 || JCS(payload) without our verifier in the loop.
  const signed = Buffer.concat([
    Buffer.from(RECEIPT_SIGNING_DOMAIN, 'utf8'),
    Buffer.from([0]),
    Buffer.from(jcsCanonicalize(receipt.payload), 'utf8'),
  ]);
  assert.ok(
    edVerify(null, signed, receipt.signature.publicKeyPem, Buffer.from(receipt.signature.signatureBase64, 'base64')),
  );
});

test('A2/A3: no binary floats anywhere; round-tripping does not change the content ID', () => {
  const { receipt } = exportOne();
  const walk = (v: unknown): void => {
    if (typeof v === 'number') {
      assert.ok(Number.isInteger(v) && !Object.is(v, -0), `non-integer number leaked: ${v}`);
    } else if (Array.isArray(v)) {
      v.forEach(walk);
    } else if (typeof v === 'object' && v !== null) {
      Object.values(v).forEach(walk);
    }
  };
  walk(receipt.payload);
  const roundTripped = JSON.parse(JSON.stringify(receipt.payload)) as Record<string, unknown>;
  const stripped: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(roundTripped)) if (k !== 'receiptId') stripped[k] = v;
  assert.equal(contentIdOf(stripped), roundTripped['receiptId']);
});

test('A5: re-evaluating the same candidate keeps candidateId, renews evaluationRunId and receiptId', () => {
  const identity = PeerIdentity.generate();
  const result = promotedCandidate();
  const opts = {
    identity,
    lineageId: uuidV7(),
    attestor: 'autogenous/governed-loop',
    start: START,
    evaluateFn: evaluate,
  };
  const a = exportEvolutionReceipts(result, opts)[0]!.payload as Record<string, unknown>;
  const b = exportEvolutionReceipts(result, opts)[0]!.payload as Record<string, unknown>;
  assert.equal(a['candidateId'], b['candidateId']);
  assert.notEqual(a['evaluationRunId'], b['evaluationRunId']);
  assert.notEqual(a['receiptId'], b['receiptId']);
});

test('A8: pairedOutcomes mirror heldOutDeltas — per-task deltas reproduce the aggregates', () => {
  const { receipt } = exportOne();
  const p = receipt.payload as Record<string, unknown>;
  const outcomes = p['pairedOutcomes'] as { taskId: string; baselineScore: string; candidateScore: string }[];
  const deltas = p['heldOutDeltas'] as string[];
  assert.equal(outcomes.length, deltas.length);
  assert.deepEqual(
    outcomes.map((o) => o.taskId),
    [...BENCH_TASK_IDS],
  );
  outcomes.forEach((o, i) => {
    assert.equal(decimal12(Number(o.candidateScore) - Number(o.baselineScore)), deltas[i]);
  });
  // The aggregate scores are the means of the encoded per-task scores.
  const mean = (xs: string[]) => decimal12(xs.reduce((s, v) => s + Number(v), 0) / xs.length);
  assert.equal(mean(outcomes.map((o) => o.baselineScore)), p['baselineScore']);
  assert.equal(mean(outcomes.map((o) => o.candidateScore)), p['candidateScore']);
});

test('A7/§5: every gate has a termVerification entry and assertions name an attestor', () => {
  const { receipt } = exportOne();
  const p = receipt.payload as Record<string, unknown>;
  const gates = p['gates'] as Record<string, boolean>;
  const terms = p['termVerification'] as { term: string; verification: string; attestor?: string }[];
  for (const gate of Object.keys(gates)) {
    const entry = terms.find((t) => t.term === gate);
    assert.ok(entry, `gate ${gate} has no termVerification entry`);
    if (entry.verification === 'trusted-assertion') {
      assert.ok(entry.attestor && entry.attestor.length > 0, `assertion for ${gate} names no attestor`);
    }
  }
});

test('the exported decision follows the CONTRACT rule, and the export re-derives the loop decision', () => {
  const identity = PeerIdentity.generate();
  const result = promotedCandidate();
  const receipts = exportEvolutionReceipts(result, {
    identity,
    lineageId: uuidV7(),
    attestor: 'autogenous/governed-loop',
    start: START,
    evaluateFn: evaluate,
  });
  for (const receipt of receipts) {
    const p = receipt.payload as Record<string, unknown>;
    const statistics = p['statistics'] as Record<string, unknown>;
    const gates = p['gates'] as Record<string, boolean>;
    const expected = statistics['accepted'] === true && Object.values(gates).every(Boolean) ? 'accepted' : 'rejected';
    assert.equal(p['decision'], expected);
    // Loop-side conjuncts all held for a promoted generation.
    assert.deepEqual(gates, { better: true, safe: true, authorized: true, reversible: true });
  }
});

// ── verifier conformance: refusals ──────────────────────────────────────

test('A1/G3: an unknown payload field is refused', () => {
  const { receipt } = exportOne();
  const smuggled = JSON.parse(JSON.stringify(receipt)) as ExportedReceipt;
  (smuggled.payload as Record<string, unknown>)['smuggled'] = true;
  assert.throws(() => verifyExportedReceipt(smuggled, [pemOf(receipt)], new Date()), /unknown field: smuggled/);
});

test('hardened bound: an oversized signatureBase64 is refused before any cryptography', () => {
  const { receipt } = exportOne();
  const oversized = JSON.parse(JSON.stringify(receipt)) as ExportedReceipt;
  oversized.signature.signatureBase64 = `${oversized.signature.signatureBase64.slice(0, 86)}AAAA==`;
  assert.throws(
    () => verifyExportedReceipt(oversized, [pemOf(receipt)], new Date()),
    /signatureBase64 outside/,
  );
});

test('B4: a signature under a different ruflo domain is refused (replay defence)', () => {
  const { receipt } = exportOne();
  const swapped = JSON.parse(JSON.stringify(receipt)) as ExportedReceipt;
  (swapped.signature as unknown as Record<string, unknown>)['domain'] = 'ruflo/flywheel-ledger-head/v1';
  assert.throws(() => verifyExportedReceipt(swapped, [pemOf(receipt)], new Date()), /domain is not the receipt domain/);
});

test('B3: a valid signature from an untrusted signer is refused, not flagged', () => {
  const { receipt } = exportOne();
  const stranger = exportOne(PeerIdentity.generate());
  assert.throws(
    () => verifyExportedReceipt(receipt, [pemOf(stranger.receipt)], new Date()),
    /signer not in trusted set/,
  );
});

test('B2: transport key order is irrelevant — a reordered payload still verifies', () => {
  const { receipt } = exportOne();
  const reordered: Record<string, unknown> = {};
  for (const key of Object.keys(receipt.payload as Record<string, unknown>).reverse()) {
    reordered[key] = (receipt.payload as Record<string, unknown>)[key];
  }
  verifyExportedReceipt({ payload: reordered, signature: receipt.signature }, [pemOf(receipt)], new Date());
});

test('F2: an unrecognized schemaVersion is refused, never best-effort parsed', () => {
  const { receipt } = exportOne();
  const bumped = JSON.parse(JSON.stringify(receipt)) as ExportedReceipt;
  (bumped.payload as Record<string, unknown>)['schemaVersion'] = 'ruflo.flywheel-receipt/v2';
  assert.throws(() => verifyExportedReceipt(bumped, [pemOf(receipt)], new Date()), /unsupported schemaVersion/);
});

test('B7: overlapping selection and promotion-holdout task IDs are refused', () => {
  const { receipt, identity } = exportOne();
  const overlapping = JSON.parse(JSON.stringify(receipt.payload)) as Record<string, unknown>;
  const evidence = overlapping['evidence'] as Record<string, unknown>;
  (evidence['corpusRoles'] as Record<string, unknown>)['promotionHoldoutTaskIds'] = [BENCH_TASK_IDS[0]];
  delete overlapping['receiptId'];
  overlapping['receiptId'] = contentIdOf(overlapping);
  const signed = Buffer.concat([
    Buffer.from(RECEIPT_SIGNING_DOMAIN, 'utf8'),
    Buffer.from([0]),
    Buffer.from(jcsCanonicalize(overlapping), 'utf8'),
  ]);
  const resigned: ExportedReceipt = {
    payload: overlapping,
    signature: {
      ...receipt.signature,
      signatureBase64: Buffer.from(identity.sign(signed), 'hex').toString('base64'),
    },
  };
  assert.throws(
    () => verifyExportedReceipt(resigned, [pemOf(receipt)], new Date()),
    /corpus roles are not disjoint/,
  );
});

// ── a live ruflo writer (v3.38.21) that breaks the number rule ──────────
//
// test/fixtures/ruflo-flywheel-receipt-v3.38.21.json was written by
// `ruflo metaharness flywheel run` (ruflo v3.38.21, @claude-flow/cli) on
// 2026-09-07 and copied verbatim. Its `candidatePolicy` carries fractional
// BINARY floats (`alpha: 0.3`, `mmrLambda: 0.5`, ...). The receipt schema
// says the policy "must still satisfy the ADR-322C number rules" and the
// spec's example receipts string their fractional knob, so this receipt is
// non-conformant and MUST be rejected — but the rejection has to name the
// offending path so the producer can fix its encoding. Re-encoding the
// knobs as decimal strings (and re-deriving the content IDs) is sufficient
// for the same receipt to verify, which is the writer-side fix.

const LIVE_FIXTURE = 'ruflo-flywheel-receipt-v3.38.21.json';

test('live ruflo receipt with binary-float policy knobs is rejected, naming candidatePolicy.alpha', () => {
  const { doc } = fixture(LIVE_FIXTURE);
  const p = doc.payload as Record<string, unknown>;
  const policy = p['candidatePolicy'] as Record<string, unknown>;
  assert.ok(Object.values(policy).some((v) => typeof v === 'number' && !Number.isInteger(v)), 'fixture must carry a fractional policy knob');
  const clock = new Date(p['issuedAt'] as string);
  assert.throws(
    () => verifyExportedReceipt(doc, [pemOf(doc)], clock),
    /binary floats for fractional values \(at \$\.candidatePolicy\.alpha: 0\.3\).*decimal string/,
  );
});

/** The writer-side fix, applied after the fact: every fractional binary
 *  float in the payload becomes a scale-12 decimal string. The live receipt
 *  has them in `candidatePolicy` AND in `evidence.verification.driftThreshold`. */
function stringifyFractions(value: unknown): unknown {
  if (typeof value === 'number' && !Number.isInteger(value)) return decimal12(value);
  if (Array.isArray(value)) return value.map(stringifyFractions);
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) out[k] = stringifyFractions(v);
    return out;
  }
  return value;
}

test('the same receipt verifies once its fractional values are decimal strings (writer-side fix)', () => {
  const { doc } = fixture(LIVE_FIXTURE);
  const identity = PeerIdentity.generate();
  const fixed = { ...doc, payload: stringifyFractions(doc.payload) as Record<string, unknown> } as ExportedReceipt;
  const policy = fixed.payload['candidatePolicy'] as Record<string, unknown>;
  assert.ok(Object.values(policy).every((v) => typeof v !== 'number' || Number.isInteger(v)));
  fixed.payload['candidateId'] = contentIdOf(policy);
  fixed.payload['baselineRef'] = fixed.payload['candidateId']; // the live run compared the champion to itself
  const stripped: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(fixed.payload)) if (k !== 'receiptId') stripped[k] = v;
  // candidateId/baselineRef seed the bootstrap, so the statistics must be recomputed too.
  const stats = fixed.payload['statistics'] as Record<string, unknown>;
  const recomputed = recomputeStatistics({
    heldOutDeltas: fixed.payload['heldOutDeltas'] as string[],
    baselineScore: fixed.payload['baselineScore'] as string,
    candidateScore: fixed.payload['candidateScore'] as string,
    frozenAnchorRegression: stats['frozenAnchorRegression'] as string,
    iterations: stats['iterations'] as number,
    corpusHash: fixed.payload['corpusHash'] as string,
    candidateId: fixed.payload['candidateId'] as string,
    baselineRef: fixed.payload['baselineRef'] as string,
    evaluationRunId: fixed.payload['evaluationRunId'] as string,
  });
  Object.assign(stats, recomputed);
  stripped['statistics'] = stats;
  fixed.payload['receiptId'] = contentIdOf(stripped);
  const signed = Buffer.concat([
    Buffer.from(RECEIPT_SIGNING_DOMAIN, 'utf8'),
    Buffer.from([0]),
    Buffer.from(jcsCanonicalize(fixed.payload), 'utf8'),
  ]);
  fixed.signature = {
    ...fixed.signature,
    publicKeyPem: derToPemLocal(identity.publicKeyDer),
    signatureBase64: Buffer.from(identity.sign(signed), 'hex').toString('base64'),
  };
  const clock = new Date(fixed.payload['issuedAt'] as string);
  const result = verifyExportedReceipt(fixed, [fixed.signature.publicKeyPem], clock);
  assert.equal(result.receiptId, fixed.payload['receiptId']);
  assert.equal(result.accepted, false, 'the live run rejected its candidate; the contract rule recomputes the same');
});

test('JCS number domain: integers only; fractional, NaN, Infinity and -0 throw with the offending path', () => {
  assert.equal(jcsCanonicalize({ b: 2, a: [1, 'x', null, true] }), '{"a":[1,"x",null,true],"b":2}');
  assert.throws(() => jcsCanonicalize({ knobs: { alpha: 0.3 } }), /at \$\.knobs\.alpha: 0\.3/);
  assert.throws(() => jcsCanonicalize([1, [2, 2.5]]), /at \$\[1\]\[1\]: 2\.5/);
  for (const bad of [Number.NaN, Number.POSITIVE_INFINITY, Number.NEGATIVE_INFINITY, -0]) {
    assert.throws(() => jcsCanonicalize({ v: bad }), /NaN, Infinity and -0 \(at \$\.v/);
  }
});

function derToPemLocal(der: Buffer): string {
  const b64 = der.toString('base64');
  const lines = b64.match(/.{1,64}/g) ?? [];
  return `-----BEGIN PUBLIC KEY-----\n${lines.join('\n')}\n-----END PUBLIC KEY-----\n`;
}

// ── canonicalization sanity against the contract's own construction ─────

test('JCS agrees with the fixture: recomputing the fixture receiptId from raw parse', () => {
  const { doc } = fixture('receipt-accepted.example.json');
  const p = doc.payload as Record<string, unknown>;
  const stripped: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(p)) if (k !== 'receiptId') stripped[k] = v;
  const digest = createHash('sha256').update(jcsCanonicalize(stripped), 'utf8').digest('hex');
  assert.equal(`sha256:${digest}`, p['receiptId']);
});
